Update termux-camera-photo

diff --git a/scripts/termux-camera-photo b/scripts/termux-camera-photo
--- a/scripts/termux-camera-photo
+++ b/scripts/termux-camera-photo
@@ -1,11 +1,10 @@
 #!@TERMUX_PREFIX@/bin/sh
 set -e -u
 
-SCRIPTNAME=termux-camera-photo
 show_usage () {
-    echo "Usage: termux-camera-photo [-c camera-id] output-file"
+    echo "Usage: ${0##*/} [-c camera-id] output-file"
     echo "Take a photo and save it to a file in JPEG format."
-    echo "  -c camera-id  ID of the camera to use (see termux-camera-info), default: 0"
+    echo "  -c camera-id  ID of the camera to use (see ${0##*/}), default: 0"
     exit 0
 }
 
@@ -16,13 +15,13 @@ do
     case "$option" in
         h) show_usage;;
         c) PARAMS="--es camera $OPTARG";;
-        ?) echo "$SCRIPTNAME: illegal option -$OPTARG"; exit 1;
+        ?) echo "${0##*/}: illegal option -$OPTARG"; exit 1;
     esac
 done
 shift $((OPTIND-1))
 
-if [ $# = 0 ]; then echo "$SCRIPTNAME: missing file argument"; exit 1; fi
-if [ $# != 1 ]; then echo "$SCRIPTNAME: too many arguments"; exit 1; fi
+if [ $# = 0 ]; then echo "${0##*/}: missing file argument"; exit 1; fi
+if [ $# != 1 ]; then echo "$${0##*/}: too many arguments"; exit 1; fi
 
 touch "$1"
 PARAMS="$PARAMS --es file `realpath $1`"
